baseURL = "https://julzinsight4.netlify.app"
languageCode = "en-us"
paginate = 6
title = "Julz Insight - Research, Innovation & Development Center"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Journal"
url = "#blog"
weight = 3
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "Latest Articles"
url = "/blog"
weight = 1

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Julz Insigh 2022"
footerLogo = "images/site-navigation/default-monochrome-white.svg"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/default-monochrome.svg"

[params.address]
email = "julzinsight@gmail.com"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/julzinsight"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/julzinsight"
weight = 2
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/julzinsight"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/julzinsight"
weight = 4
